name: CI

on:
  push:
    branches: [master, main]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for affected commands

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      # Set SHAs for nx affected commands
      - uses: nrwl/nx-set-shas@v4

      # Run affected tasks
      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --ci --code-coverage
      - run: npx nx affected -t build --parallel=3
